//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestNetFrameworkDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMCloseEntities : DbContext
    {
        public CRMCloseEntities()
            : base("name=CRMCloseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<ConditionTheUser> ConditionTheUser { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<IdentetyTown> IdentetyTown { get; set; }
        public virtual DbSet<ListMessage> ListMessage { get; set; }
        public virtual DbSet<ListRequestsAtUser> ListRequestsAtUser { get; set; }
        public virtual DbSet<ListUserChats> ListUserChats { get; set; }
        public virtual DbSet<LoginANDPasswordUsers> LoginANDPasswordUsers { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<RequestCondition> RequestCondition { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<RequestsAddress> RequestsAddress { get; set; }
        public virtual DbSet<RequestsCategory> RequestsCategory { get; set; }
        public virtual DbSet<RequestsUrgency> RequestsUrgency { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Town> Town { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserCategory> UserCategory { get; set; }
        public virtual DbSet<UserRoleINRequest> UserRoleINRequest { get; set; }
    }
}
