//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestNetFrameworkDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListRequestsAtUser
    {
        public int listRequestsAtUserID { get; set; }
        public int listRequestsAtUserUserID_fk_ { get; set; }
        public int listRequestsAtUserRequestID_fk_ { get; set; }
        public int listRequestsAtUserUserRole_fk_ { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual User User { get; set; }
        public virtual UserRoleINRequest UserRoleINRequest { get; set; }
    }
}
