//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestNetFrameworkDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestsAddress()
        {
            this.Requests = new HashSet<Requests>();
        }
    
        public int requestsAddressID { get; set; }
        public int requestsAdressTown_fk_ { get; set; }
        public int requestAdressStreet_fk_ { get; set; }
        public string requestAdressBuilding { get; set; }
        public int requestAsressNumberHouse { get; set; }
    
        public virtual IdentetyTown IdentetyTown { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests> Requests { get; set; }
        public virtual Street Street { get; set; }
    }
}
