//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestNetFrameworkDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.ListRequestsAtUser = new HashSet<ListRequestsAtUser>();
        }
    
        public int requestsID { get; set; }
        public string requestsName { get; set; }
        public string requestsDescription { get; set; }
        public int requestsCategoryID_fk_ { get; set; }
        public int requestsUrgencyID_fk_ { get; set; }
        public int requestsAddressID_fk_ { get; set; }
        public int requestsCabinetNumber { get; set; }
        public int requestsChatID_fk_ { get; set; }
        public int requestConditionID_fk_ { get; set; }
        public Nullable<int> requestScore { get; set; }
    
        public virtual Chat Chat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListRequestsAtUser> ListRequestsAtUser { get; set; }
        public virtual RequestCondition RequestCondition { get; set; }
        public virtual RequestsAddress RequestsAddress { get; set; }
        public virtual RequestsCategory RequestsCategory { get; set; }
        public virtual RequestsUrgency RequestsUrgency { get; set; }
    }
}
