//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestNetFrameworkDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ListRequestsAtUser = new HashSet<ListRequestsAtUser>();
            this.ListUserChats = new HashSet<ListUserChats>();
        }
    
        public int userID { get; set; }
        public int userLoginANDPassword_fk_ { get; set; }
        public int userCondition_fk_ { get; set; }
        public int userDepartament_fk_ { get; set; }
        public int userCategory_fk_ { get; set; }
        public string userName { get; set; }
        public string userPatranymic { get; set; }
        public string userSurname { get; set; }
        public System.DateTime userDateCreate { get; set; }
        public string userNumberPhone { get; set; }
    
        public virtual ConditionTheUser ConditionTheUser { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListRequestsAtUser> ListRequestsAtUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListUserChats> ListUserChats { get; set; }
        public virtual LoginANDPasswordUsers LoginANDPasswordUsers { get; set; }
        public virtual UserCategory UserCategory { get; set; }
    }
}
